2019-05-28 21:24:50,215 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-28 21:24:50,216 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-28-21-24-50-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-28 21:24:50,216 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-28 21:24:50,216 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-28 21:24:50,216 : INFO : Machine : Platform: win32
2019-05-28 21:24:50,216 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-28 21:24:50,216 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-28 21:24:50,216 : INFO : Machine : Machine config file #1: config.yaml
2019-05-28 21:24:50,218 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-28 21:24:50,220 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-28 21:24:50,221 : INFO : Machine : Initialise MPF.
2019-05-28 21:24:50,279 : DEBUG : FAST : Configuring FAST hardware.
2019-05-28 21:24:50,476 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-05-28 21:24:50,525 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-05-28 21:24:50,525 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,525 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,526 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-05-28 21:24:50,589 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-05-28 21:24:50,637 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-05-28 21:24:50,638 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,638 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,639 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,719 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-28 21:24:50,729 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 1353, 'prev_value': None, 'change': True}
2019-05-28 21:24:50,729 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:24:50,730 : INFO : EventManager : Event: ======'machine_var_player3_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:24:50,730 : INFO : EventManager : Event: ======'machine_var_player4_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-28 21:24:50,730 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,730 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,730 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-28 21:24:50,731 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-28 21:24:50,806 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\410e2f069e995e601a053ae1f865a8d9.mpf_cache
2019-05-28 21:24:50,868 : DEBUG : ModeController : Loaded mode bonus
2019-05-28 21:24:50,869 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\f394a72c4810bb1cc42cac0690a90dcf.mpf_cache
2019-05-28 21:24:50,872 : DEBUG : ModeController : Loaded mode gameoverplayer
2019-05-28 21:24:50,873 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6cbeeb809d9de6fbbf2951c4e6867473.mpf_cache
2019-05-28 21:24:50,887 : DEBUG : ModeController : Loaded mode darkworld
2019-05-28 21:24:50,888 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\d9d23a2a9a3117f1553491692ff1c689.mpf_cache
2019-05-28 21:24:50,898 : DEBUG : ModeController : Loaded mode playfield_multiplier
2019-05-28 21:24:50,899 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-28 21:24:50,903 : DEBUG : ModeController : Loaded mode light_world
2019-05-28 21:24:50,904 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\aecceeb5afbfdc7257044e8417ebcf98.mpf_cache
2019-05-28 21:24:50,917 : DEBUG : ModeController : Loaded mode attract
2019-05-28 21:24:50,917 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fc30620fce8f82c18fed051cdde27ef9.mpf_cache
2019-05-28 21:24:50,921 : DEBUG : ModeController : Loaded mode 5waycombotracker
2019-05-28 21:24:50,921 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\225554da95d8871f7382aa94a6d6b3eb.mpf_cache
2019-05-28 21:24:50,925 : DEBUG : ModeController : Loaded mode lost_woods_starter
2019-05-28 21:24:50,954 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dbd150f896646081271b7a77a791f2fa.mpf_cache
2019-05-28 21:24:50,966 : DEBUG : ModeController : Loaded mode slide_tracker
2019-05-28 21:24:50,966 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\683810c84ecff8b3923f4991066156d6.mpf_cache
2019-05-28 21:24:50,970 : DEBUG : ModeController : Loaded mode mode_player
2019-05-28 21:24:50,970 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-05-28 21:24:50,974 : DEBUG : ModeController : Loaded mode bomb_finder
2019-05-28 21:24:50,974 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\34c6448537d1c95c89cf73a07c0f99c9.mpf_cache
2019-05-28 21:24:50,980 : DEBUG : ModeController : Loaded mode bottle_filler
2019-05-28 21:24:50,981 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-05-28 21:24:50,989 : DEBUG : ModeController : Loaded mode game
2019-05-28 21:24:50,989 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6caaa2c03f737135abd403644138525e.mpf_cache
2019-05-28 21:24:50,995 : DEBUG : ModeController : Loaded mode shop
2019-05-28 21:24:50,995 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c35ad2e595070cac0b6f696d6f7f6af6.mpf_cache
2019-05-28 21:24:50,999 : DEBUG : ModeController : Loaded mode ball_save
2019-05-28 21:24:50,999 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\562f2c62ffb495bc414930beede29530.mpf_cache
2019-05-28 21:24:51,045 : DEBUG : ModeController : Loaded mode game_ender_mode
2019-05-28 21:24:51,045 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58a9cd5447353eacedab412f1c10b0ab.mpf_cache
2019-05-28 21:24:51,049 : DEBUG : ModeController : Loaded mode lost_woods
2019-05-28 21:24:51,049 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\43a06f52d0e9cf0597140b4c27159d40.mpf_cache
2019-05-28 21:24:51,053 : DEBUG : ModeController : Loaded mode escapehurryup
2019-05-28 21:24:51,053 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\4afc9f23ca6340163a8bb51d7deea78f.mpf_cache
2019-05-28 21:24:51,068 : DEBUG : ModeController : Loaded mode base
2019-05-28 21:24:51,069 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\cb8b20150020107be74f23a2ee427f56.mpf_cache
2019-05-28 21:24:51,077 : DEBUG : ModeController : Loaded mode high_score
2019-05-28 21:24:51,077 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-05-28 21:24:51,081 : DEBUG : ModeController : Loaded mode video_player
2019-05-28 21:24:51,081 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-05-28 21:24:51,085 : DEBUG : ModeController : Loaded mode 2ballescape
2019-05-28 21:24:51,085 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dd39e2de39eb354a1ec99be2f3167765.mpf_cache
2019-05-28 21:24:51,089 : DEBUG : ModeController : Loaded mode heartmeter
2019-05-28 21:24:51,089 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6eb8b6e4728e10ce756703e43167d298.mpf_cache
2019-05-28 21:24:51,093 : DEBUG : ModeController : Loaded mode rupee2x_finder
2019-05-28 21:24:51,093 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\ee4432fc011abe94968ff81513361e18.mpf_cache
2019-05-28 21:24:51,097 : DEBUG : ModeController : Loaded mode final_hold
2019-05-28 21:24:51,097 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\05768db999abb9e30be16a432a0581c8.mpf_cache
2019-05-28 21:24:51,101 : DEBUG : ModeController : Loaded mode extraball
2019-05-28 21:24:51,101 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\3485f9bf4bb8d1d21be6de1438e091ba.mpf_cache
2019-05-28 21:24:51,116 : DEBUG : ModeController : Loaded mode skillshot_ballsave
2019-05-28 21:24:51,116 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\27a949ddf2d3e5eeb9247bd991aba200.mpf_cache
2019-05-28 21:24:51,120 : DEBUG : ModeController : Loaded mode darkworld2
2019-05-28 21:24:51,120 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\1f8ff34a8859f8c62d77912f33e29b9c.mpf_cache
2019-05-28 21:24:51,124 : DEBUG : ModeController : Loaded mode 2ballqualifier
2019-05-28 21:24:51,124 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-28 21:24:51,124 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml.
2019-05-28 21:24:51,125 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml
2019-05-28 21:24:51,352 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...olumn 13\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...olumn 13\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 523, column 13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 523, column 13'
2019-05-28 21:24:51,360 : INFO : Machine : Starting the main run loop.
2019-05-28 21:24:51,361 : INFO : Machine : Shutting down...
2019-05-28 21:24:51,361 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-28 21:24:51,363 : ERROR : FAST : Stop called on serial connection \\.\COM12
2019-05-28 21:24:51,364 : ERROR : FAST : Stop called on serial connection \\.\COM11
2019-05-28 21:24:51,735 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 523, column 13'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 523, column 13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\item_tracker\config\item_tracker.yaml: 'Key "repeat" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\item_tracker\\config\\item_tracker.yaml", line 523, column 13'
