2019-03-19 20:05:55,735 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.12
2019-03-19 20:05:55,735 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs\\2019-03-19-20-05-55-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2019-03-19 20:05:55,735 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-03-19 20:05:55,735 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-03-19 20:05:55,735 : INFO : Machine : Platform: win32
2019-03-19 20:05:55,736 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-03-19 20:05:55,736 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-03-19 20:05:56,198 : INFO : Machine : Machine config file #1: config.yaml
2019-03-19 20:05:56,200 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\config\config.yaml
2019-03-19 20:05:56,200 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-03-19 20:05:56,201 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-03-19 20:05:56,298 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-03-19 20:05:56,300 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\config.yaml.
2019-03-19 20:05:56,300 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\config.yaml
2019-03-19 20:05:56,334 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\config.yaml
2019-03-19 20:05:56,335 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\hardware.yaml
2019-03-19 20:05:56,505 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\hardware.yaml
2019-03-19 20:05:56,509 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-03-19 20:05:56,522 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-03-19 20:05:56,525 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\videos.yaml
2019-03-19 20:05:56,577 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\videos.yaml
2019-03-19 20:05:56,587 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-03-19 20:05:56,589 : DEBUG : asyncio : Using selector: SelectSelector
2019-03-19 20:05:56,590 : INFO : Machine : Initialise MPF.
2019-03-19 20:05:56,617 : DEBUG : FAST : Configuring FAST hardware.
2019-03-19 20:05:56,790 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-03-19 20:05:56,823 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-03-19 20:05:56,823 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-03-19 20:05:56,823 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-03-19 20:05:56,824 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-03-19 20:05:56,887 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-03-19 20:05:56,935 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-03-19 20:05:56,935 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-03-19 20:05:56,936 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-03-19 20:05:56,936 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-03-19 20:05:56,999 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-03-19 20:05:57,001 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 25, 'prev_value': None, 'change': True}
2019-03-19 20:05:57,001 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.50.12', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,001 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.50.12, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,001 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-03-19 20:05:57,002 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-03-19 20:05:57,053 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58a9cd5447353eacedab412f1c10b0ab.mpf_cache
2019-03-19 20:05:57,056 : DEBUG : ModeController : Loaded mode lost_woods
2019-03-19 20:05:57,057 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-03-19 20:05:57,059 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-03-19 20:05:57,060 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\e44f2e5e1ef00181aa9bc27df94a0c3d.mpf_cache
2019-03-19 20:05:57,061 : DEBUG : ModeController : Loaded mode escape_starter
2019-03-19 20:05:57,062 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\916c9e2d9177837f45e9cdbb7c1d0b93.mpf_cache
2019-03-19 20:05:57,064 : DEBUG : ModeController : Loaded mode unusual_show_tracker
2019-03-19 20:05:57,065 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-03-19 20:05:57,068 : DEBUG : ModeController : Loaded mode bomb_finder
2019-03-19 20:05:57,068 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-03-19 20:05:57,071 : DEBUG : ModeController : Loaded mode video_player
2019-03-19 20:05:57,071 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\a31feedcb4b85bf76d76fe6a1222bc90.mpf_cache
2019-03-19 20:05:57,074 : DEBUG : ModeController : Loaded mode agahnim_multiball
2019-03-19 20:05:57,074 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\86e0d165ea95889c95b56598c3ebe263.mpf_cache
2019-03-19 20:05:57,077 : DEBUG : ModeController : Loaded mode music_player
2019-03-19 20:05:57,077 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6cbeeb809d9de6fbbf2951c4e6867473.mpf_cache
2019-03-19 20:05:57,082 : DEBUG : ModeController : Loaded mode darkworld
2019-03-19 20:05:57,082 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-03-19 20:05:57,086 : DEBUG : ModeController : Loaded mode 2ballescape
2019-03-19 20:05:57,087 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\28e1731e516595966b3afcb08910cb63.mpf_cache
2019-03-19 20:05:57,090 : DEBUG : ModeController : Loaded mode heart_tracker
2019-03-19 20:05:57,090 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fd6423453738b6cee138971698f65579.mpf_cache
2019-03-19 20:05:57,094 : DEBUG : ModeController : Loaded mode mode_tracker
2019-03-19 20:05:57,094 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6fd2b5e36bbbd9c12f9ee3aa32f1ceca.mpf_cache
2019-03-19 20:05:57,099 : DEBUG : ModeController : Loaded mode ball_hold_tracker
2019-03-19 20:05:57,099 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fc30620fce8f82c18fed051cdde27ef9.mpf_cache
2019-03-19 20:05:57,103 : DEBUG : ModeController : Loaded mode 5waycombotracker
2019-03-19 20:05:57,103 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\05768db999abb9e30be16a432a0581c8.mpf_cache
2019-03-19 20:05:57,107 : DEBUG : ModeController : Loaded mode extraball
2019-03-19 20:05:57,107 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-03-19 20:05:57,110 : DEBUG : ModeController : Loaded mode light_world
2019-03-19 20:05:57,110 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-03-19 20:05:57,121 : DEBUG : ModeController : Loaded mode game
2019-03-19 20:05:57,121 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\43a06f52d0e9cf0597140b4c27159d40.mpf_cache
2019-03-19 20:05:57,125 : DEBUG : ModeController : Loaded mode escapehurryup
2019-03-19 20:05:57,125 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c3fd2c292a6c0d3463ad9b4555730ad5.mpf_cache
2019-03-19 20:05:57,129 : DEBUG : ModeController : Loaded mode item_tracker
2019-03-19 20:05:57,130 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml
2019-03-19 20:05:57,130 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml.
2019-03-19 20:05:57,130 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml
2019-03-19 20:05:57,169 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml
2019-03-19 20:05:57,169 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml.
2019-03-19 20:05:57,169 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml
2019-03-19 20:05:57,202 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml
2019-03-19 20:05:57,202 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...fig files.',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...fig files.',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 147, in _load_config_file_and_return_loaded_files
    if config_type not in ConfigValidator.config_spec[k][
KeyError: 'video_player'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 113, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 262, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 180, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 156, in _load_config_file_and_return_loaded_files
    'files.'.format(k, filename, config_type))
ValueError: Found a "video_player:" section in config file C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml, but that section is not valid in mode config files.
2019-03-19 20:05:57,375 : ERROR : root : Exception is not set.
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 661, in run
    self.initialise_mpf()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 653, in initialise_mpf
    if init.exception():
asyncio.base_futures.InvalidStateError: Exception is not set.
