2019-03-21 18:44:42,870 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.12
2019-03-21 18:44:42,871 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs\\2019-03-21-18-44-42-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2019-03-21 18:44:42,871 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-03-21 18:44:42,871 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-03-21 18:44:42,871 : INFO : Machine : Platform: win32
2019-03-21 18:44:42,871 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-03-21 18:44:42,872 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-03-21 18:44:43,601 : INFO : Machine : Machine config file #1: config.yaml
2019-03-21 18:44:43,603 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-03-21 18:44:43,606 : DEBUG : asyncio : Using selector: SelectSelector
2019-03-21 18:44:43,607 : INFO : Machine : Initialise MPF.
2019-03-21 18:44:43,651 : DEBUG : FAST : Configuring FAST hardware.
2019-03-21 18:44:43,910 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-03-21 18:44:43,958 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-03-21 18:44:43,958 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-03-21 18:44:43,959 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-03-21 18:44:43,959 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-03-21 18:44:44,022 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-03-21 18:44:44,071 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-03-21 18:44:44,071 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,071 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,072 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,174 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-03-21 18:44:44,177 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 8, 'prev_value': None, 'change': True}
2019-03-21 18:44:44,178 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.50.12', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,178 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.50.12, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,178 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-03-21 18:44:44,179 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-03-21 18:44:44,258 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\10a6a590bbb9b0438569045f4aac79d9.mpf_cache
2019-03-21 18:44:44,262 : DEBUG : ModeController : Loaded mode escape
2019-03-21 18:44:44,263 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fc30620fce8f82c18fed051cdde27ef9.mpf_cache
2019-03-21 18:44:44,266 : DEBUG : ModeController : Loaded mode 5waycombotracker
2019-03-21 18:44:44,267 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\1f8ff34a8859f8c62d77912f33e29b9c.mpf_cache
2019-03-21 18:44:44,271 : DEBUG : ModeController : Loaded mode 2ballqualifier
2019-03-21 18:44:44,272 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-03-21 18:44:44,272 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml.
2019-03-21 18:44:44,273 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-03-21 18:44:44,349 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\light_world\config\light_world.yaml
2019-03-21 18:44:44,351 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-03-21 18:44:44,355 : DEBUG : ModeController : Loaded mode light_world
2019-03-21 18:44:44,355 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58a9cd5447353eacedab412f1c10b0ab.mpf_cache
2019-03-21 18:44:44,359 : DEBUG : ModeController : Loaded mode lost_woods
2019-03-21 18:44:44,360 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-03-21 18:44:44,360 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\base\config\base.yaml.
2019-03-21 18:44:44,360 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-03-21 18:44:44,418 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-03-21 18:44:44,419 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\4afc9f23ca6340163a8bb51d7deea78f.mpf_cache
2019-03-21 18:44:44,423 : DEBUG : ModeController : Loaded mode base
2019-03-21 18:44:44,423 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-03-21 18:44:44,428 : DEBUG : ModeController : Loaded mode video_player
2019-03-21 18:44:44,429 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c35ad2e595070cac0b6f696d6f7f6af6.mpf_cache
2019-03-21 18:44:44,433 : DEBUG : ModeController : Loaded mode ball_save
2019-03-21 18:44:44,434 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\225554da95d8871f7382aa94a6d6b3eb.mpf_cache
2019-03-21 18:44:44,438 : DEBUG : ModeController : Loaded mode lost_woods_starter
2019-03-21 18:44:44,439 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\f394a72c4810bb1cc42cac0690a90dcf.mpf_cache
2019-03-21 18:44:44,443 : DEBUG : ModeController : Loaded mode gameoverplayer
2019-03-21 18:44:44,444 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\7b0dcc699efc7732bf9d3e57ee202517.mpf_cache
2019-03-21 18:44:44,448 : DEBUG : ModeController : Loaded mode 2ballescape
2019-03-21 18:44:44,450 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\aecceeb5afbfdc7257044e8417ebcf98.mpf_cache
2019-03-21 18:44:44,459 : DEBUG : ModeController : Loaded mode attract
2019-03-21 18:44:44,460 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\fd6423453738b6cee138971698f65579.mpf_cache
2019-03-21 18:44:44,464 : DEBUG : ModeController : Loaded mode mode_tracker
2019-03-21 18:44:44,465 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-03-21 18:44:44,469 : DEBUG : ModeController : Loaded mode bomb_finder
2019-03-21 18:44:44,470 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\28e1731e516595966b3afcb08910cb63.mpf_cache
2019-03-21 18:44:44,474 : DEBUG : ModeController : Loaded mode heart_tracker
2019-03-21 18:44:44,475 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\916c9e2d9177837f45e9cdbb7c1d0b93.mpf_cache
2019-03-21 18:44:44,479 : DEBUG : ModeController : Loaded mode unusual_show_tracker
2019-03-21 18:44:44,480 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c3fd2c292a6c0d3463ad9b4555730ad5.mpf_cache
2019-03-21 18:44:44,483 : DEBUG : ModeController : Loaded mode item_tracker
2019-03-21 18:44:44,483 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6fd2b5e36bbbd9c12f9ee3aa32f1ceca.mpf_cache
2019-03-21 18:44:44,487 : DEBUG : ModeController : Loaded mode ball_hold_tracker
2019-03-21 18:44:44,488 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-03-21 18:44:44,492 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-03-21 18:44:44,493 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dd39e2de39eb354a1ec99be2f3167765.mpf_cache
2019-03-21 18:44:44,497 : DEBUG : ModeController : Loaded mode heartmeter
2019-03-21 18:44:44,497 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\86e0d165ea95889c95b56598c3ebe263.mpf_cache
2019-03-21 18:44:44,502 : DEBUG : ModeController : Loaded mode music_player
2019-03-21 18:44:44,503 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6cbeeb809d9de6fbbf2951c4e6867473.mpf_cache
2019-03-21 18:44:44,508 : DEBUG : ModeController : Loaded mode darkworld
2019-03-21 18:44:44,509 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\e44f2e5e1ef00181aa9bc27df94a0c3d.mpf_cache
2019-03-21 18:44:44,513 : DEBUG : ModeController : Loaded mode escape_starter
2019-03-21 18:44:44,514 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dbd150f896646081271b7a77a791f2fa.mpf_cache
2019-03-21 18:44:44,518 : DEBUG : ModeController : Loaded mode slide_tracker
2019-03-21 18:44:44,519 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-03-21 18:44:44,529 : DEBUG : ModeController : Loaded mode game
2019-03-21 18:44:44,530 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\05768db999abb9e30be16a432a0581c8.mpf_cache
2019-03-21 18:44:44,534 : DEBUG : ModeController : Loaded mode extraball
2019-03-21 18:44:44,535 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml
2019-03-21 18:44:44,535 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml.
2019-03-21 18:44:44,535 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml
2019-03-21 18:44:44,579 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\high_score\config\high_score.yaml
2019-03-21 18:44:44,580 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml.
2019-03-21 18:44:44,580 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml
2019-03-21 18:44:44,629 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 1\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 1\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 194, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 220, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 59, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 68, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 481, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "sound_player" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\high_score\\config\\high_score.yaml", line 136, column 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 113, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 262, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 180, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 208, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\high_score\config\high_score.yaml: 'Key "sound_player" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\high_score\\config\\high_score.yaml", line 136, column 1'
2019-03-21 18:44:44,919 : ERROR : root : Exception is not set.
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 661, in run
    self.initialise_mpf()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 653, in initialise_mpf
    if init.exception():
asyncio.base_futures.InvalidStateError: Exception is not set.
